from enum import Enum


class Languages(Enum):
    """
    Supported allowed_languages names
    """
    ARAB = "Arab"
    ENGLISH = "English"
    HEBREW = "Hebrew"
    ITALIAN = "Italian"

    DEFAULT = ENGLISH

    @property
    def is_rtl(self) -> bool:
        """
        :return: True if this language is written left-to-right
        """
        return self in [Languages.ARAB, Languages.HEBREW]

class Orientations(object):
    """
    Orientations
    """

    HORIZONTAL = "horizontal"
    VERTICAL = "vertical"


class PhobiaTypes(Enum):
    """
    Types of phobias
    """
    ANIMAL_PHOBIAS = "ANIMAL_PHOBIAS"
    PLANT_PHOBIAS = "PLANT_PHOBIAS"
    MICROORGANISM_PHOBIAS = "MICROORGANISM_PHOBIAS"
    BODY_PHOBIAS = "BODY_PHOBIAS"
    PEOPLE_PHOBIAS = "PEOPLE_PHOBIAS"
    PERSONNEL_AND_KIN_PHOBIAS = "PERSONNEL_AND_KIN_PHOBIAS"
    NAMES_AND_SPECIFIC_PEOPLE_PHOBIAS = "NAMES_AND_SPECIFIC_PEOPLE_PHOBIAS"
    DEMOGRAPHICS_PHOBIAS = "DEMOGRAPHICS_PHOBIAS"
    RELIGOUS_PHOBIAS = "RELIGOUS_PHOBIAS"
    PLACES_PHOBIAS = "PLACES_PHOBIAS"
    EVENTS_AND_ACTIONS_PHOBIAS = "EVENTS_AND_ACTIONS_PHOBIAS"
    MONTHS_PHOBIAS = "MONTHS_PHOBIAS"
    HOLIDAY_PHOBIAS = "HOLIDAY_PHOBIAS"
    SPECIFIC_DAY_PHOBIAS = "SPECIFIC_DAY_PHOBIAS"
    EMOTIONS_PHOBIAS = "EMOTIONS_PHOBIAS"
    DISEASES_AND_DISORDERS_PHOBIAS = "DISEASES_AND_DISORDERS_PHOBIAS"
    THINGS_PHOBIAS = "THINGS_PHOBIAS"
    SUBSTANCE_PHOBIAS = "SUBSTANCE_PHOBIAS"
    FOOD_AND_DRINK_PHOBIAS = "FOOD_AND_DRINK_PHOBIAS"
    VEHICLE_PHOBIAS = "VEHICLE_PHOBIAS"
    CONDITION_AND_QUALITY_PHOBIAS = "CONDITION_AND_QUALITY_PHOBIAS"
    GENRES_PHOBIAS = "GENRES_PHOBIAS"
    MOVIES_AND_TV_SHOW_PHOBIAS = "MOVIES_AND_TV_SHOW_PHOBIAS"
    WEATHER_PHOBIAS = "WEATHER_PHOBIAS"
    NATURAL_DISASTER_PHOBIAS = "NATURAL_DISASTER_PHOBIAS"
    SPACE_PHOBIAS = "SPACE_PHOBIAS"
    PLANET_PHOBIAS = "PLANET_PHOBIAS"
    COLOR_PHOBIAS = "COLOR_PHOBIAS"
    LANGUAGE_PHOBIAS = "LANGUAGE_PHOBIAS"
    LETTERS_PHOBIAS = "LETTERS_PHOBIAS"
    WORD_PHOBIAS = "WORD_PHOBIAS"
    PUNCTUATION_MARK_PHOBIAS = "PUNCTUATION_MARK_PHOBIAS"
    NUMERICAL_PHOBIAS = "NUMERICAL_PHOBIAS"
    SHAPE_PHOBIAS = "SHAPE_PHOBIAS"
    LEGENDARY_BEINGS_PHOBIAS = "LEGENDARY_BEINGS_PHOBIAS"
    FICTIONAL_CHARACTER_PHOBIAS = "FICTIONAL_CHARACTER_PHOBIAS"
    COMPANY_PHOBIAS = "COMPANY_PHOBIAS"
    SPORTS_TOYS_GAME_AND_VIDEOGAME_PHOBIAS = "SPORTS_TOYS_GAME_AND_VIDEOGAME_PHOBIAS"
    OTHER_PHOBIAS = "OTHER_PHOBIAS"
    JOKE_AND_FICTIONAL_PHOBIAS = "JOKE_AND_FICTIONAL_PHOBIAS"
    STAR_PHOBIAS = "STAR_PHOBIAS"


class PhobiaExplanations(Enum):
    """
    Explanations of phobias
    """
    FEAR_OF_PEOPLE_AND_PUNISHMENTS = "FEAR_OF_PEOPLE_AND_PUNISHMENTS"
    PAST_LIFE_TRAUMAS = "PAST_LIFE_TRAUMAS"
    FEAR_OF_INNOCENT_STIMULATION = "FEAR_OF_INNOCENT_STIMULATION"
    FEAR_OFLOWER_SPIRITUAL_WORLD = "FEAR_OFLOWER_SPIRITUAL_WORLD"
    FEAR_OF_SPIRITUAL_WORLD = "FEAR_OF_SPIRITUAL_WORLD"
    POSSESSION_AND_OBSESSION = "POSSESSION_AND_OBSESSION"
    LACK_OF_ENERGY = "LACK_OF_ENERGY"
    FEAR_OF_ABANDONMENT = "FEAR_OF_ABANDONMENT"
    FEAR_OF_LOVE_OR_SEPARATION = "FEAR_OF_LOVE_OR_SEPARATION"
    FEAR_OF_PHYSICAL_HURT = "FEAR_OF_PHYSICAL_HURT"
    FEAR_OF_DISEASE = "FEAR_OF_DISEASE"
    SEXUAL_ABUSE_AND_TRAUMA = "SEXUAL_ABUSE_AND_TRAUMA"
    GENITAL_SECRETION_RELATED = "GENITAL_SECRETION_RELATED"


class Texts(object):
    """
    Texts in the system
    """
    ADD_PHOBIA = "Add Phobia"
    ADD_NAME = "Add Name"
    ADD_PERSON = "Add Person"
    BACK = "Back"
    DELETE = "Delete"
    EDIT = "Edit"
    EDIT_PERSON = "Edit Person"
    EDIT_NAME = "Edit Name"
    FIRST_NAMES = "First Names"
    FULL_NAME = "Full Name"
    LANGUAGE = "Language"
    LAST_NAMES = "Last Names"
    MANAGE_PEOPLE = "Manage People"
    NAMES = "Names"
    PEOPLE = "People"
    PHOBIAS = "Phobias"
    SAVE = "Save"
    SELECT = "Select"
    SETTINGS = "Settings"
