from enum import Enum


class Languages(Enum):
    """
    Supported allowed_languages names
    """
    ARAB = "ARAB"
    ENGLISH = "ENGLISH"
    HEBREW = "HEBREW"
    ITALIAN = "ITALIAN"

    DEFAULT = ENGLISH


class Orientations(object):
    """
    Orientations
    """

    HORIZONTAL = "horizontal"
    VERTICAL = "vertical"


class PhobiaTypes(Enum):
    """
    Types of phobias
    """
    ANIMAL_PHOBIAS = "ANIMAL_PHOBIAS"
    PLANT_PHOBIAS = "PLANT_PHOBIAS"
    MICROORGANISM_PHOBIAS = "MICROORGANISM_PHOBIAS"
    BODY_PHOBIAS = "BODY_PHOBIAS"
    PEOPLE_PHOBIAS = "PEOPLE_PHOBIAS"
    PERSONNEL_AND_KIN_PHOBIAS = "PERSONNEL_AND_KIN_PHOBIAS"
    NAMES_AND_SPECIFIC_PEOPLE_PHOBIAS = "NAMES_AND_SPECIFIC_PEOPLE_PHOBIAS"
    DEMOGRAPHICS_PHOBIAS = "DEMOGRAPHICS_PHOBIAS"
    RELIGOUS_PHOBIAS = "RELIGOUS_PHOBIAS"
    PLACES_PHOBIAS = "PLACES_PHOBIAS"
    EVENTS_AND_ACTIONS_PHOBIAS = "EVENTS_AND_ACTIONS_PHOBIAS"
    MONTHS_PHOBIAS = "MONTHS_PHOBIAS"
    HOLIDAY_PHOBIAS = "HOLIDAY_PHOBIAS"
    SPECIFIC_DAY_PHOBIAS = "SPECIFIC_DAY_PHOBIAS"
    EMOTIONS_PHOBIAS = "EMOTIONS_PHOBIAS"
    DISEASES_AND_DISORDERS_PHOBIAS = "DISEASES_AND_DISORDERS_PHOBIAS"
    THINGS_PHOBIAS = "THINGS_PHOBIAS"
    SUBSTANCE_PHOBIAS = "SUBSTANCE_PHOBIAS"
    FOOD_AND_DRINK_PHOBIAS = "FOOD_AND_DRINK_PHOBIAS"
    VEHICLE_PHOBIAS = "VEHICLE_PHOBIAS"
    CONDITION_AND_QUALITY_PHOBIAS = "CONDITION_AND_QUALITY_PHOBIAS"
    GENRES_PHOBIAS = "GENRES_PHOBIAS"
    MOVIES_AND_TV_SHOW_PHOBIAS = "MOVIES_AND_TV_SHOW_PHOBIAS"
    WEATHER_PHOBIAS = "WEATHER_PHOBIAS"
    NATURAL_DISASTER_PHOBIAS = "NATURAL_DISASTER_PHOBIAS"
    SPACE_PHOBIAS = "SPACE_PHOBIAS"
    PLANET_PHOBIAS = "PLANET_PHOBIAS"
    COLOR_PHOBIAS = "COLOR_PHOBIAS"
    LANGUAGE_PHOBIAS = "LANGUAGE_PHOBIAS"
    LETTERS_PHOBIAS = "LETTERS_PHOBIAS"
    WORD_PHOBIAS = "WORD_PHOBIAS"
    PUNCTUATION_MARK_PHOBIAS = "PUNCTUATION_MARK_PHOBIAS"
    NUMERICAL_PHOBIAS = "NUMERICAL_PHOBIAS"
    SHAPE_PHOBIAS = "SHAPE_PHOBIAS"
    LEGENDARY_BEINGS_PHOBIAS = "LEGENDARY_BEINGS_PHOBIAS"
    FICTIONAL_CHARACTER_PHOBIAS = "FICTIONAL_CHARACTER_PHOBIAS"
    COMPANY_PHOBIAS = "COMPANY_PHOBIAS"
    SPORTS_TOYS_GAME_AND_VIDEOGAME_PHOBIAS = "SPORTS_TOYS_GAME_AND_VIDEOGAME_PHOBIAS"
    OTHER_PHOBIAS = "OTHER_PHOBIAS"
    JOKE_AND_FICTIONAL_PHOBIAS = "JOKE_AND_FICTIONAL_PHOBIAS"
    STAR_PHOBIAS = "STAR_PHOBIAS"
